// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: can_message.proto
// Protobuf Java Version: 4.32.0

package org.example.utils.proto;

@com.google.protobuf.Generated
public final class CanMessage {
  private CanMessage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      CanMessage.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CanMessageProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.utils.proto.CanMessageProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * CAN ID，16进制字符串，如"0x12345678"
     * </pre>
     *
     * <code>string can_id = 1;</code>
     * @return The canId.
     */
    String getCanId();
    /**
     * <pre>
     * CAN ID，16进制字符串，如"0x12345678"
     * </pre>
     *
     * <code>string can_id = 1;</code>
     * @return The bytes for canId.
     */
    com.google.protobuf.ByteString
        getCanIdBytes();

    /**
     * <pre>
     * 数据，16进制字符串，每两位代表一个字节
     * </pre>
     *
     * <code>string data = 2;</code>
     * @return The data.
     */
    String getData();
    /**
     * <pre>
     * 数据，16进制字符串，每两位代表一个字节
     * </pre>
     *
     * <code>string data = 2;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <pre>
     * 时间戳字符串
     * </pre>
     *
     * <code>string time = 3;</code>
     * @return The time.
     */
    String getTime();
    /**
     * <pre>
     * 时间戳字符串
     * </pre>
     *
     * <code>string time = 3;</code>
     * @return The bytes for time.
     */
    com.google.protobuf.ByteString
        getTimeBytes();
  }
  /**
   * <pre>
   * 单个CAN消息
   * </pre>
   *
   * Protobuf type {@code org.example.utils.proto.CanMessageProto}
   */
  public static final class CanMessageProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.example.utils.proto.CanMessageProto)
      CanMessageProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        CanMessageProto.class.getName());
    }
    // Use CanMessageProto.newBuilder() to construct.
    private CanMessageProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CanMessageProto() {
      canId_ = "";
      data_ = "";
      time_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CanMessage.internal_static_org_example_utils_proto_CanMessageProto_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CanMessage.internal_static_org_example_utils_proto_CanMessageProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CanMessageProto.class, Builder.class);
    }

    public static final int CAN_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object canId_ = "";
    /**
     * <pre>
     * CAN ID，16进制字符串，如"0x12345678"
     * </pre>
     *
     * <code>string can_id = 1;</code>
     * @return The canId.
     */
    @Override
    public String getCanId() {
      Object ref = canId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        canId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * CAN ID，16进制字符串，如"0x12345678"
     * </pre>
     *
     * <code>string can_id = 1;</code>
     * @return The bytes for canId.
     */
    @Override
    public com.google.protobuf.ByteString
        getCanIdBytes() {
      Object ref = canId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        canId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object data_ = "";
    /**
     * <pre>
     * 数据，16进制字符串，每两位代表一个字节
     * </pre>
     *
     * <code>string data = 2;</code>
     * @return The data.
     */
    @Override
    public String getData() {
      Object ref = data_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 数据，16进制字符串，每两位代表一个字节
     * </pre>
     *
     * <code>string data = 2;</code>
     * @return The bytes for data.
     */
    @Override
    public com.google.protobuf.ByteString
        getDataBytes() {
      Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object time_ = "";
    /**
     * <pre>
     * 时间戳字符串
     * </pre>
     *
     * <code>string time = 3;</code>
     * @return The time.
     */
    @Override
    public String getTime() {
      Object ref = time_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        time_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 时间戳字符串
     * </pre>
     *
     * <code>string time = 3;</code>
     * @return The bytes for time.
     */
    @Override
    public com.google.protobuf.ByteString
        getTimeBytes() {
      Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(canId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, canId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, data_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(time_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, time_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(canId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, canId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(data_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, data_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(time_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, time_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CanMessageProto)) {
        return super.equals(obj);
      }
      CanMessageProto other = (CanMessageProto) obj;

      if (!getCanId()
          .equals(other.getCanId())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getTime()
          .equals(other.getTime())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CAN_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCanId().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + getTime().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CanMessageProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CanMessageProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CanMessageProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CanMessageProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CanMessageProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CanMessageProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CanMessageProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CanMessageProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static CanMessageProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static CanMessageProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CanMessageProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CanMessageProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CanMessageProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 单个CAN消息
     * </pre>
     *
     * Protobuf type {@code org.example.utils.proto.CanMessageProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.utils.proto.CanMessageProto)
        CanMessageProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CanMessage.internal_static_org_example_utils_proto_CanMessageProto_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CanMessage.internal_static_org_example_utils_proto_CanMessageProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CanMessageProto.class, Builder.class);
      }

      // Construct using org.example.utils.proto.CanMessage.CanMessageProto.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        canId_ = "";
        data_ = "";
        time_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CanMessage.internal_static_org_example_utils_proto_CanMessageProto_descriptor;
      }

      @Override
      public CanMessageProto getDefaultInstanceForType() {
        return CanMessageProto.getDefaultInstance();
      }

      @Override
      public CanMessageProto build() {
        CanMessageProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CanMessageProto buildPartial() {
        CanMessageProto result = new CanMessageProto(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(CanMessageProto result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.canId_ = canId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.data_ = data_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.time_ = time_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CanMessageProto) {
          return mergeFrom((CanMessageProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CanMessageProto other) {
        if (other == CanMessageProto.getDefaultInstance()) return this;
        if (!other.getCanId().isEmpty()) {
          canId_ = other.canId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getTime().isEmpty()) {
          time_ = other.time_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                canId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                data_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                time_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object canId_ = "";
      /**
       * <pre>
       * CAN ID，16进制字符串，如"0x12345678"
       * </pre>
       *
       * <code>string can_id = 1;</code>
       * @return The canId.
       */
      public String getCanId() {
        Object ref = canId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          canId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * CAN ID，16进制字符串，如"0x12345678"
       * </pre>
       *
       * <code>string can_id = 1;</code>
       * @return The bytes for canId.
       */
      public com.google.protobuf.ByteString
          getCanIdBytes() {
        Object ref = canId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          canId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * CAN ID，16进制字符串，如"0x12345678"
       * </pre>
       *
       * <code>string can_id = 1;</code>
       * @param value The canId to set.
       * @return This builder for chaining.
       */
      public Builder setCanId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        canId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * CAN ID，16进制字符串，如"0x12345678"
       * </pre>
       *
       * <code>string can_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCanId() {
        canId_ = getDefaultInstance().getCanId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * CAN ID，16进制字符串，如"0x12345678"
       * </pre>
       *
       * <code>string can_id = 1;</code>
       * @param value The bytes for canId to set.
       * @return This builder for chaining.
       */
      public Builder setCanIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        canId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object data_ = "";
      /**
       * <pre>
       * 数据，16进制字符串，每两位代表一个字节
       * </pre>
       *
       * <code>string data = 2;</code>
       * @return The data.
       */
      public String getData() {
        Object ref = data_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 数据，16进制字符串，每两位代表一个字节
       * </pre>
       *
       * <code>string data = 2;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 数据，16进制字符串，每两位代表一个字节
       * </pre>
       *
       * <code>string data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数据，16进制字符串，每两位代表一个字节
       * </pre>
       *
       * <code>string data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        data_ = getDefaultInstance().getData();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数据，16进制字符串，每两位代表一个字节
       * </pre>
       *
       * <code>string data = 2;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        data_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private Object time_ = "";
      /**
       * <pre>
       * 时间戳字符串
       * </pre>
       *
       * <code>string time = 3;</code>
       * @return The time.
       */
      public String getTime() {
        Object ref = time_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 时间戳字符串
       * </pre>
       *
       * <code>string time = 3;</code>
       * @return The bytes for time.
       */
      public com.google.protobuf.ByteString
          getTimeBytes() {
        Object ref = time_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          time_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 时间戳字符串
       * </pre>
       *
       * <code>string time = 3;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        time_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 时间戳字符串
       * </pre>
       *
       * <code>string time = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        time_ = getDefaultInstance().getTime();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 时间戳字符串
       * </pre>
       *
       * <code>string time = 3;</code>
       * @param value The bytes for time to set.
       * @return This builder for chaining.
       */
      public Builder setTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        time_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.example.utils.proto.CanMessageProto)
    }

    // @@protoc_insertion_point(class_scope:org.example.utils.proto.CanMessageProto)
    private static final CanMessageProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CanMessageProto();
    }

    public static CanMessageProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CanMessageProto>
        PARSER = new com.google.protobuf.AbstractParser<CanMessageProto>() {
      @Override
      public CanMessageProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CanMessageProto> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CanMessageProto> getParserForType() {
      return PARSER;
    }

    @Override
    public CanMessageProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CanMessageListProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.utils.proto.CanMessageListProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
     */
    java.util.List<CanMessageProto>
        getMessagesList();
    /**
     * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
     */
    CanMessageProto getMessages(int index);
    /**
     * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
     */
    int getMessagesCount();
    /**
     * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
     */
    java.util.List<? extends CanMessageProtoOrBuilder>
        getMessagesOrBuilderList();
    /**
     * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
     */
    CanMessageProtoOrBuilder getMessagesOrBuilder(
        int index);
  }
  /**
   * <pre>
   * CAN消息列表，用于批量存储
   * </pre>
   *
   * Protobuf type {@code org.example.utils.proto.CanMessageListProto}
   */
  public static final class CanMessageListProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.example.utils.proto.CanMessageListProto)
      CanMessageListProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        CanMessageListProto.class.getName());
    }
    // Use CanMessageListProto.newBuilder() to construct.
    private CanMessageListProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CanMessageListProto() {
      messages_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CanMessage.internal_static_org_example_utils_proto_CanMessageListProto_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CanMessage.internal_static_org_example_utils_proto_CanMessageListProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CanMessageListProto.class, Builder.class);
    }

    public static final int MESSAGES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<CanMessageProto> messages_;
    /**
     * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
     */
    @Override
    public java.util.List<CanMessageProto> getMessagesList() {
      return messages_;
    }
    /**
     * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
     */
    @Override
    public java.util.List<? extends CanMessageProtoOrBuilder>
        getMessagesOrBuilderList() {
      return messages_;
    }
    /**
     * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
     */
    @Override
    public int getMessagesCount() {
      return messages_.size();
    }
    /**
     * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
     */
    @Override
    public CanMessageProto getMessages(int index) {
      return messages_.get(index);
    }
    /**
     * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
     */
    @Override
    public CanMessageProtoOrBuilder getMessagesOrBuilder(
        int index) {
      return messages_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < messages_.size(); i++) {
        output.writeMessage(1, messages_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < messages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, messages_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CanMessageListProto)) {
        return super.equals(obj);
      }
      CanMessageListProto other = (CanMessageListProto) obj;

      if (!getMessagesList()
          .equals(other.getMessagesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMessagesCount() > 0) {
        hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
        hash = (53 * hash) + getMessagesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CanMessageListProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CanMessageListProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CanMessageListProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CanMessageListProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CanMessageListProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CanMessageListProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CanMessageListProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CanMessageListProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static CanMessageListProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static CanMessageListProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CanMessageListProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CanMessageListProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CanMessageListProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * CAN消息列表，用于批量存储
     * </pre>
     *
     * Protobuf type {@code org.example.utils.proto.CanMessageListProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.utils.proto.CanMessageListProto)
        CanMessageListProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CanMessage.internal_static_org_example_utils_proto_CanMessageListProto_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CanMessage.internal_static_org_example_utils_proto_CanMessageListProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CanMessageListProto.class, Builder.class);
      }

      // Construct using org.example.utils.proto.CanMessage.CanMessageListProto.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
        } else {
          messages_ = null;
          messagesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CanMessage.internal_static_org_example_utils_proto_CanMessageListProto_descriptor;
      }

      @Override
      public CanMessageListProto getDefaultInstanceForType() {
        return CanMessageListProto.getDefaultInstance();
      }

      @Override
      public CanMessageListProto build() {
        CanMessageListProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CanMessageListProto buildPartial() {
        CanMessageListProto result = new CanMessageListProto(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(CanMessageListProto result) {
        if (messagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            messages_ = java.util.Collections.unmodifiableList(messages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.messages_ = messages_;
        } else {
          result.messages_ = messagesBuilder_.build();
        }
      }

      private void buildPartial0(CanMessageListProto result) {
        int from_bitField0_ = bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CanMessageListProto) {
          return mergeFrom((CanMessageListProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CanMessageListProto other) {
        if (other == CanMessageListProto.getDefaultInstance()) return this;
        if (messagesBuilder_ == null) {
          if (!other.messages_.isEmpty()) {
            if (messages_.isEmpty()) {
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMessagesIsMutable();
              messages_.addAll(other.messages_);
            }
            onChanged();
          }
        } else {
          if (!other.messages_.isEmpty()) {
            if (messagesBuilder_.isEmpty()) {
              messagesBuilder_.dispose();
              messagesBuilder_ = null;
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              messagesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetMessagesFieldBuilder() : null;
            } else {
              messagesBuilder_.addAllMessages(other.messages_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                CanMessageProto m =
                    input.readMessage(
                        CanMessageProto.parser(),
                        extensionRegistry);
                if (messagesBuilder_ == null) {
                  ensureMessagesIsMutable();
                  messages_.add(m);
                } else {
                  messagesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<CanMessageProto> messages_ =
        java.util.Collections.emptyList();
      private void ensureMessagesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          messages_ = new java.util.ArrayList<CanMessageProto>(messages_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          CanMessageProto, CanMessageProto.Builder, CanMessageProtoOrBuilder> messagesBuilder_;

      /**
       * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
       */
      public java.util.List<CanMessageProto> getMessagesList() {
        if (messagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(messages_);
        } else {
          return messagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
       */
      public int getMessagesCount() {
        if (messagesBuilder_ == null) {
          return messages_.size();
        } else {
          return messagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
       */
      public CanMessageProto getMessages(int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);
        } else {
          return messagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
       */
      public Builder setMessages(
          int index, CanMessageProto value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.set(index, value);
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
       */
      public Builder setMessages(
          int index, CanMessageProto.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.set(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
       */
      public Builder addMessages(CanMessageProto value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
       */
      public Builder addMessages(
          int index, CanMessageProto value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(index, value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
       */
      public Builder addMessages(
          CanMessageProto.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
       */
      public Builder addMessages(
          int index, CanMessageProto.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
       */
      public Builder addAllMessages(
          Iterable<? extends CanMessageProto> values) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, messages_);
          onChanged();
        } else {
          messagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
       */
      public Builder clearMessages() {
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
       */
      public Builder removeMessages(int index) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.remove(index);
          onChanged();
        } else {
          messagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
       */
      public CanMessageProto.Builder getMessagesBuilder(
          int index) {
        return internalGetMessagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
       */
      public CanMessageProtoOrBuilder getMessagesOrBuilder(
          int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);  } else {
          return messagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
       */
      public java.util.List<? extends CanMessageProtoOrBuilder>
           getMessagesOrBuilderList() {
        if (messagesBuilder_ != null) {
          return messagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(messages_);
        }
      }
      /**
       * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
       */
      public CanMessageProto.Builder addMessagesBuilder() {
        return internalGetMessagesFieldBuilder().addBuilder(
            CanMessageProto.getDefaultInstance());
      }
      /**
       * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
       */
      public CanMessageProto.Builder addMessagesBuilder(
          int index) {
        return internalGetMessagesFieldBuilder().addBuilder(
            index, CanMessageProto.getDefaultInstance());
      }
      /**
       * <code>repeated .org.example.utils.proto.CanMessageProto messages = 1;</code>
       */
      public java.util.List<CanMessageProto.Builder>
           getMessagesBuilderList() {
        return internalGetMessagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          CanMessageProto, CanMessageProto.Builder, CanMessageProtoOrBuilder>
          internalGetMessagesFieldBuilder() {
        if (messagesBuilder_ == null) {
          messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              CanMessageProto, CanMessageProto.Builder, CanMessageProtoOrBuilder>(
                  messages_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          messages_ = null;
        }
        return messagesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.example.utils.proto.CanMessageListProto)
    }

    // @@protoc_insertion_point(class_scope:org.example.utils.proto.CanMessageListProto)
    private static final CanMessageListProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CanMessageListProto();
    }

    public static CanMessageListProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CanMessageListProto>
        PARSER = new com.google.protobuf.AbstractParser<CanMessageListProto>() {
      @Override
      public CanMessageListProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CanMessageListProto> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CanMessageListProto> getParserForType() {
      return PARSER;
    }

    @Override
    public CanMessageListProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_utils_proto_CanMessageProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_utils_proto_CanMessageProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_utils_proto_CanMessageListProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_utils_proto_CanMessageListProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021can_message.proto\022\027org.example.utils.p" +
      "roto\"=\n\017CanMessageProto\022\016\n\006can_id\030\001 \001(\t\022" +
      "\014\n\004data\030\002 \001(\t\022\014\n\004time\030\003 \001(\t\"Q\n\023CanMessag" +
      "eListProto\022:\n\010messages\030\001 \003(\0132(.org.examp" +
      "le.utils.proto.CanMessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_utils_proto_CanMessageProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_utils_proto_CanMessageProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_utils_proto_CanMessageProto_descriptor,
        new String[] { "CanId", "Data", "Time", });
    internal_static_org_example_utils_proto_CanMessageListProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_example_utils_proto_CanMessageListProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_utils_proto_CanMessageListProto_descriptor,
        new String[] { "Messages", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
