package org.example.utils.event;

public enum EventString {
    START_RECEIVE_DATA("START_RECEIVE_DATA"),
    STOP_RECEIVE_DATA("STOP_RECEIVE_DATA"),
    UPDATE_TABLE("UPDATE_TABLE"),
    UPDATE_TABLE_FILTER("UPDATE_TABLE_FILTER"),
    UPDATE_TABLE_FILTER_CONFIG("UPDATE_TABLE_FILTER_CONFIG"),
    UPDATE_TABLE_FILTER_CONFIG_FINISH("UPDATE_TABLE_FILTER_CONFIG_FINISH"),
    // 板子连接，发布板子的地址
    BOARD_CONNECT("BOARD_CONNECT"),

    TCP_START_SEND("TCP_START_SEND"),
    // 接收队列是空了的事件发生
    DATA_QUEUE_IDLE("DATA_QUEUE_IDLE"),

    UPDATE_VALUE_CHANGE_CONFIG("UPDATE_VALUE_CHANGE_CONFIG"),

    REFRESS_RECEIVE_DATA_COUNTER("REFRESS_RECEIVE_DATA_COUNTER"),

    VALUE_CHANGED("VALUE_CHANGED");



    EventString(String updateTableFilterConfig) {

    }
}
